
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

cds:
  data-source.auto-config.enabled: false

logging:
  level:
    customer.cap_java_composition_delete_test.handlers: INFO
    root: INFO
